export const test: string
export const ramiro: string
export const register: string
export const content: string
export const login: string
export const list: string
export const coin: string
export const price: string
export const pedra: string
