export const test: string
export const ramiro: string
export const register: string
export const content: string
export const login: string
export const list: string
export const coin: string
export const price: string
export const pedra: string
export const logoLogin: string
export const work: string
export const profile: string
export const profilePhoto: string
export const IconMap: string
export const MarkerProfile: string
export const listMarker: string
export const desc: string
export const priceMarker: string
export const pedraMarker: string
export const coinMarker: string