language: node_js 

node_js:
  - 8

before_install:
    - echo 32 
install:
    - yarn install
script:
    - yarn build 
deploy:
  provider: pages
  local_dir: dist/
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: true 
