language: node_js 

node_js:
  - 8

before_install:
    - echo "qualquer coisa que eu desejar" 
install:
    - yarn install
script:
    - yarn build 
    - yarn test
    - yarn lint || true

deploy:
  provider: pages
  local_dir: dist/
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master || develop 
